### PR TITLE
Update MUMPS.jl to conform with julia v4.0

### PR DESCRIPTION
**Pull request by kenno**
Hello

I have updated MUMPS.jl syntax to work with julia v4.0. There is no functionality change.
Please ignore this pull request if you still want MUMPS.jl to work with julia v3.0.

Thanks.

### CODE REVIEW

**Comment by dpo** [comment]
Is this to avoid deprecation warnings? Both Julia 0.3 and 0.4 could be used if you added `Compat.jl` directives.

**Comment by kenno** [comment]
Yes, to avoid deprecation warnings. Thanks for the suggestion about Compat.jl. I have updated MUMPS.jl using Compat. Tested with Julia v0.3.12 and v0.4.1.

**Comment by dpo** [comment]
Thanks, that looks good. I'm not sure why Travis isn't kicking it to build your changes. But I would like to ask that pull requests be made against the `develop` branch. Would you mind rebasing? Also it would be great if you could squash your commits together. Thanks!

**Comment by kenno** [comment]
Okay, no problem. I'm going to close this existing pull request and create a new one against `develop` branch.

**Pull request closed without merging**
